Refactor steamos-update to simplify distro-specific implementations

diff --git a/usr/bin/steamos-update b/usr/bin/steamos-update
--- a/usr/bin/steamos-update
+++ b/usr/bin/steamos-update
@@ -7,20 +7,33 @@
 # steamos-update --enable-duplicate-detection       -- should perform an update
 # steamos-update                                    -- should perform an update
 
-# Hook for custom OS script
-for OS_UPDATE_SCRIPT in \
-    "/usr/lib/os-update" \
-    "/usr/libexec/os-update"
-do
-    if [ -f "$OS_UPDATE_SCRIPT" ]; then
-        exec "${OS_UPDATE_SCRIPT}" "$@"
-    fi
-done
+# This script will call /usr/libexec/ogc/os-update with a single argument, either "check" or "update".
+# Steam expects the custom os-update script to function as follows.
+#
+# For check:
+# - If there is no update available, exit with code 7
+# - If there is an update available, print "Update available: <VERSION>" and exit with code 0
+#   Steam displays "<VERSION>" when developer mode is enabled
+# - If there is an error, exit with a non-zero code other than 7
+#
+# For update:
+# - Begin the OS update process and continuously output the percentage completion as
+#   an integer value between 0-100 followed by a '%' character and newline
+# - If the update completes successfully, exit with code 0
+# - If there is an error, exit with a non-zero code other than 7
 
+OS_UPDATE_SCRIPT=/usr/libexec/ogc/os-update
+
+# Process arguments from Steam
+ACTION=update
 while [[ $# -gt 0 ]]; do
   case $1 in
+    check)
+      ACTION=check
+      shift
+      ;;
     --supports-duplicate-detection)
-      EXIT=1
+      EXIT=yes
       shift
       ;;
     *)
@@ -29,9 +42,12 @@ while [[ $# -gt 0 ]]; do
   esac
 done
 
-# Exit gracefully if no script was found
-if [ -n "$EXIT" ]; then
-  exit 0
-elif
-  exit 7 
+if [ -n "${EXIT}" ]; then
+	exit 0
 fi
+
+if [ ! -f "${OS_UPDATE_SCRIPT}" ]; then
+	exit 7
+fi
+
+exec "${OS_UPDATE_SCRIPT}" "${ACTION}"
